groups:
- name: postgres_alerts
  rules:
  - alert: PostgresqlDown
    expr: pg_up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "PostgreSQL down on {{ $labels.instance }}"
      description: "PostgreSQL instance is down on {{ $labels.instance }}"

  - alert: PostgresqlHighConnections
    expr: sum by (datname) (pg_stat_activity_count{datname!~"template.*|postgres"}) > pg_settings_max_connections * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high connections on {{ $labels.instance }}"
      description: "PostgreSQL instance has used more than 80% of available connections on {{ $labels.instance }} for database {{ $labels.datname }}"

  - alert: PostgresqlSlowQueries
    expr: pg_stat_activity_max_tx_duration{datname!~"template.*|postgres"} > 60
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL slow queries on {{ $labels.instance }}"
      description: "PostgreSQL instance has queries running for more than 60 seconds on {{ $labels.instance }} for database {{ $labels.datname }}"

  - alert: PostgresqlHighRollbacks
    expr: rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres"}[5m]) / (rate(pg_stat_database_xact_commit{datname!~"template.*|postgres"}[5m]) + rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres"}[5m])) > 0.05
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL high rollback rate on {{ $labels.instance }}"
      description: "PostgreSQL instance has a rollback rate higher than 5% on {{ $labels.instance }} for database {{ $labels.datname }}"

  - alert: PostgresqlHighCacheHitRatio
    expr: (1 - sum by (datname) (rate(pg_stat_database_blks_read{datname!~"template.*|postgres"}[5m])) / sum by (datname) (rate(pg_stat_database_blks_hit{datname!~"template.*|postgres"}[5m]) + rate(pg_stat_database_blks_read{datname!~"template.*|postgres"}[5m]))) < 0.95
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "PostgreSQL low cache hit ratio on {{ $labels.instance }}"
      description: "PostgreSQL instance has a cache hit ratio lower than 95% on {{ $labels.instance }} for database {{ $labels.datname }}"
