global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - "rules/django_rules.yml"
  - "rules/node_rules.yml"
  - "rules/postgres_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jw-attendant-scheduler-staging"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["jw-staging:8001"]
        labels:
          env: "staging"
          app: "jw-attendant-scheduler"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["jw-staging:9100"]
        labels:
          env: "staging"
          instance: "jw-staging"

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["jw-staging:9187"]
        labels:
          env: "staging"
          db: "jw_attendant_db"
