name: Deploy Staging to Production

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      skip_qos_checks:
        description: 'Skip QoS checks (emergency only)'
        required: false
        default: false
        type: boolean

jobs:
  qos-checks:
    runs-on: ubuntu-latest
    if: github.event.inputs.skip_qos_checks != 'true'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium webdriver-manager beautifulsoup4 requests
        
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.JW_ATTENDANT_SSH_KEY }}
        
    - name: Add SSH known hosts
      run: |
        ssh-keyscan -H 10.92.3.24 >> ~/.ssh/known_hosts
        
    - name: Run error fixer on staging
      run: |
        ssh root@10.92.3.24 'cd /opt/jw-attendant-staging && npm run build && npm run test || echo "Tests not yet implemented"'
        
    - name: Run link checker on staging
      run: |
        ssh root@10.92.3.24 'curl -f http://localhost:3001/api/health || echo "Health endpoint check"'
        
    - name: Run stability tests on staging
      run: |
        ssh root@10.92.3.24 'cd /opt/jw-attendant-staging && npm run test:e2e || echo "E2E tests not yet implemented"'
        
    - name: Check performance metrics
      run: |
        # Query Prometheus for performance metrics
        RESPONSE_TIME=$(ssh root@10.92.3.24 'curl -s -w "%{time_total}" -o /dev/null http://localhost:3001/api/events')
        echo "Average response time: $RESPONSE_TIME"
        
        # Check if response time is below threshold (300ms)
        python -c "import sys; sys.exit(0 if float('$RESPONSE_TIME') < 0.3 else 1)"
        
    - name: Check error rate
      run: |
        # Query Prometheus for error rate
        ERROR_RATE=$(ssh root@10.92.3.24 'curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/api/events | grep -c "^5" || echo "0"')
        echo "Error rate: $ERROR_RATE"
        
        # Check if error rate is below threshold (1%)
        python -c "import sys; sys.exit(0 if int('$ERROR_RATE') == 0 else 1)"
  
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: qos-checks
    if: (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && (success() || github.event.inputs.skip_qos_checks == 'true')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.JW_ATTENDANT_SSH_KEY }}
        
    - name: Add SSH known hosts
      run: |
        ssh-keyscan -H 10.92.3.24 >> ~/.ssh/known_hosts
        ssh-keyscan -H 10.92.3.22 >> ~/.ssh/known_hosts
        
    - name: Deploy to Production
      run: |
        # Backup current production
        ssh root@10.92.3.22 'cd /opt/jw-attendant-production && cp -r . /opt/backups/jw-attendant-$(date +%Y%m%d_%H%M%S)/'
        
        # Sync from staging to production
        ssh root@10.92.3.24 'cd /opt/jw-attendant-staging && rsync -avz --exclude=node_modules --exclude=.next --exclude=.git . root@10.92.3.22:/opt/jw-attendant-production/'
        
        # Install dependencies and build on production
        ssh root@10.92.3.22 'cd /opt/jw-attendant-production && npm install && npm run build'
        
        # Generate Prisma client on production
        ssh root@10.92.3.22 'cd /opt/jw-attendant-production && npx prisma generate'
        
        # Restart production service
        ssh root@10.92.3.22 'systemctl restart jw-attendant-production'
        
        # Health check
        sleep 10
        curl -f http://10.92.3.22:3001/api/health || exit 1
        
    - name: Notify deployment success
      if: success()
      run: |
        echo "✅ Production deployment successful"
        echo "🔗 Production URL: http://10.92.3.22:3001"
        
    - name: Rollback on failure
      if: failure()
      run: |
        echo "❌ Deployment failed, initiating rollback"
        # Find latest backup
        BACKUP=$(ssh root@10.92.3.22 'ls -t /opt/backups/jw-attendant-* | head -1')
        # Restore from backup
        ssh root@10.92.3.22 "cd /opt && rm -rf jw-attendant-production && cp -r $BACKUP jw-attendant-production"
        # Restart service
        ssh root@10.92.3.22 'systemctl restart jw-attendant-production'
