# Generated by Django 4.2.5 on 2025-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='jw_status',
        ),
        migrations.AddField(
            model_name='attendant',
            name='serving_as',
            field=models.JSONField(blank=True, default=list, help_text='List of organizational positions (Elder, Ministerial Servant, Regular Pioneer, etc.)'),
        ),
    ]
