# Generated by Django 4.2.5 on 2025-08-27 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_attendant_jw_status_attendant_serving_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='attendant',
            name='preferred_positions',
        ),
        migrations.AddField(
            model_name='attendant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether attendant is active for current event'),
        ),
        migrations.AddField(
            model_name='attendant',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Assigned supervisor (Overseer, Assistant Overseer, or Keyman)', limit_choices_to={'serving_as__overlap': ['overseer', 'assistant_overseer', 'keyman']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_attendants', to='scheduler.attendant'),
        ),
        migrations.AlterField(
            model_name='attendant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
