# Generated by Django 4.2.5 on 2025-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_attendant_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
