# Generated by Django 4.2.5 on 2025-08-27 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_attendant_email'),
    ]

    operations = [
    ]
