# Generated by Django 4.2.5 on 2025-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20250827_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendant',
            name='email',
            field=models.EmailField(blank=True, null=True, unique=True),
        ),
    ]
