# Generated by Django 4.2.5 on 2025-08-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_allow_null_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendant',
            options={},
        ),
        migrations.CreateModel(
            name='LanyardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.PositiveIntegerField()),
                ('checked_out', models.BooleanField(default=False)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('assembly_overseer', models.CharField(blank=True, max_length=100)),
                ('attendant_overseer', models.CharField(blank=True, max_length=100)),
                ('overseer_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.attendant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lanyard_assignments', to='scheduler.event')),
            ],
            options={
                'ordering': ['badge_number'],
                'unique_together': {('event', 'badge_number')},
            },
        ),
    ]
