# Generated by Django 4.2.5 on 2025-08-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_attendant_options_lanyardassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendant',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='attendant',
            name='oversight',
            field=models.ForeignKey(blank=True, help_text='Assigned oversight (Overseer, Assistant Overseer, or Keyman)', limit_choices_to={'serving_as__overlap': ['overseer', 'assistant_overseer', 'keyman']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oversight_attendants', to='scheduler.attendant'),
        ),
    ]
