# Generated by Django 4.2.5 on 2025-08-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_remove_attendant_supervisor_attendant_oversight'),
    ]

    operations = [
    ]
