# Generated by Django 4.2.5 on 2025-08-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_rename_supervisor_to_oversight'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_enabled', models.BooleanField(default=False, help_text='Enable Gmail API integration for sending emails')),
                ('gmail_credentials_uploaded', models.BooleanField(default=False, help_text='Whether Gmail credentials file has been uploaded')),
                ('gmail_authenticated', models.BooleanField(default=False, help_text='Whether Gmail API has been authenticated')),
                ('site_name', models.CharField(default='JW Attendant Scheduler', help_text='Name displayed in email templates', max_length=100)),
                ('from_name', models.CharField(default='Event Coordination Team', help_text='Name displayed as email sender', max_length=100)),
                ('send_invitation_emails', models.BooleanField(default=True, help_text='Send email invitations to new users')),
                ('send_assignment_notifications', models.BooleanField(default=False, help_text='Send email notifications for new assignments')),
                ('send_event_reminders', models.BooleanField(default=False, help_text='Send email reminders for upcoming events')),
                ('test_email_address', models.EmailField(blank=True, help_text='Email address for testing email functionality', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.RemoveField(
            model_name='lanyardassignment',
            name='assembly_overseer',
        ),
        migrations.RemoveField(
            model_name='lanyardassignment',
            name='attendant_overseer',
        ),
        migrations.RemoveField(
            model_name='lanyardassignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lanyardassignment',
            name='overseer_phone',
        ),
        migrations.RemoveField(
            model_name='lanyardassignment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lanyardassignment',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.attendant'),
        ),
        migrations.AlterField(
            model_name='lanyardassignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.event'),
        ),
    ]
