# Generated by Django 4.2.5 on 2025-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_emailconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfiguration',
            name='encrypted_gmail_app_password',
            field=models.TextField(blank=True, help_text='Encrypted Gmail App Password (16-character password from Google)'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='encrypted_gmail_token',
            field=models.TextField(blank=True, help_text='Encrypted Gmail OAuth2 token (stored securely)'),
        ),
        migrations.AddField(
            model_name='emailconfiguration',
            name='gmail_email',
            field=models.EmailField(blank=True, help_text='Gmail address for sending emails', max_length=254),
        ),
    ]
