# Generated by Django 4.2.5 on 2025-08-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_add_app_password_fields'),
        ('scheduler', '0011_emailconfiguration_encrypted_gmail_app_password_and_more'),
    ]

    operations = [
    ]
