# Generated by Django 4.2.5 on 2025-08-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_merge_20250827_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendant',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='Events this attendant is associated with', related_name='attendants', to='scheduler.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this event was archived', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When this event was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this event was marked as completed', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('current', 'Current'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='upcoming', max_length=15),
        ),
    ]
