# Generated by Django 4.2.5 on 2025-09-06 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_attendant_events_event_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text="e.g., 'Morning Count', 'Afternoon Count'", max_length=50)),
                ('count_time', models.DateTimeField(help_text='When the count should be taken')),
                ('is_completed', models.BooleanField(default=False)),
                ('total_count', models.PositiveIntegerField(blank=True, help_text='Auto-calculated total from position counts', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_sessions', to='scheduler.event')),
            ],
            options={
                'ordering': ['count_time'],
                'unique_together': {('event', 'session_name', 'count_time')},
            },
        ),
        migrations.CreateModel(
            name='EventPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.PositiveIntegerField(help_text='Position number (1-53)')),
                ('position_name', models.CharField(blank=True, help_text="Optional name for position (e.g., 'Main Gate', 'Parking Lot A')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='scheduler.event')),
            ],
            options={
                'ordering': ['position_number'],
                'unique_together': {('event', 'position_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='PositionShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scheduler.eventposition')),
            ],
            options={
                'ordering': ['shift_start'],
            },
        ),
        migrations.CreateModel(
            name='PositionCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, help_text='Count for this position', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_counts', to='scheduler.countsession')),
                ('entered_by', models.ForeignKey(blank=True, help_text='Oversight member who entered the count', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counts', to='scheduler.eventposition')),
            ],
            options={
                'ordering': ['position__position_number'],
                'unique_together': {('count_session', 'position')},
            },
        ),
    ]
